import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read = (path) => readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const migration = read("supabase/migrations/20260825131301_furnace_v1.sql");
const page = read("global-cash-graph/index.html");
const client = read("global-cash-graph/graph.js");
assert.match(migration, /lifetime_money_burned double precision not null default 0/);
assert.match(migration, /select money[\s\S]*for update/);
assert.match(migration, /money = greatest\(0, money - v_amount\)/);
assert.match(migration, /lifetime_money_burned = lifetime_money_burned \+ v_amount/);
assert.doesNotMatch(migration, /lifetime_earnings\s*=/);
assert.match(migration, /perform public\.snapshot_global_cash\(\)/);
const leaderboardQuery = migration.match(/create or replace function public\.get_top_money_burners[\s\S]*?\$\$;/)?.[0] ?? "";
assert.match(leaderboardQuery, /p\.leaderboard_hidden = false/);
assert.match(leaderboardQuery, /order by p\.lifetime_money_burned desc, p\.username\s+limit/);
assert.match(leaderboardQuery, /limit least\(greatest\(coalesce\(p_limit, 10\), 1\), 100\)/);
assert.match(page, /Highest lifetime totals from players visible on public leaderboards\./);
assert.match(page, /data-furnace-quick="1000000"/);
assert.match(page, /data-furnace-quick="10000000"/);
assert.match(page, /data-furnace-quick="100000000"/);
assert.match(page, /data-furnace-max/);
assert.match(client, /confirmDialog/);
assert.match(client, /tone: "danger"/);
assert.match(client, /data\.leaderboard\.map/);
assert.doesNotMatch(client, /data\.leaderboard\.(?:filter|sort)\(/);
console.log("Furnace V1 tests passed.");
await import("./cash-chart-display-test.mjs");
